# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  

jobs:
  test:

    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      fail-fast: true
      matrix:
        # In order to effectively specify Rails and Ruby versions simultaneously,
        # we specify every tuple of versions in `include` section
        # except for the tuples with a particular Rails version.
        #
        # The objective of the exception is to satisfy the
        # constraint that a matrix cannot be empty.
        #
        # We test only the oldest and latest Ruby versions for each Rails version.
        gemfile: [gemfiles/rails_7.0.gemfile]
        ruby: ['2.7', '3']
        include:
          - gemfile: gemfiles/rails_7.1.gemfile
            ruby: '2.7' # minimum required version for rails 7.1
          - gemfile: gemfiles/rails_7.1.gemfile
            ruby: '3' # latest ruby version

          - gemfile: gemfiles/rails_7.2.gemfile
            ruby: '3.1' # minimum required version for rails 7.2
          - gemfile: gemfiles/rails_7.2.gemfile
            ruby: '3' # latest ruby version

          - gemfile: gemfiles/rails_8.0.gemfile
            ruby: '3.2' # minimum required version for rails 8.0
          - gemfile: gemfiles/rails_8.0.gemfile
            ruby: '3' # latest ruby version

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    services:
      mysql:
        image: ghcr.io/dena/ubuntu22-mysql-q4m:8.0.28-6bc571978335b6304566c8df4a5ff7e2b2d9911f
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
